###형태를 합치기 위해 재 구조화

In [12]:
import pandas as pd
import numpy as np
obj1 = pd.Series([40,10,20,30],index=list('가나다라'))
obj1.sort_values(ascending=False)

가    40
라    30
다    20
나    10
dtype: int64

In [13]:
obj1.argsort() #인덱스가 아닌 포지션 레이블

가    1
나    2
다    3
라    0
dtype: int64

In [14]:
obj1.idxmin()

'나'

In [15]:
obj1.idxmax()

'가'

In [19]:
obj2=pd.Series([40,10,20,30],index=list('cabd'))
obj2

c    40
a    10
b    20
d    30
dtype: int64

In [21]:
#슬라이딩 하기 전에 정렬 해야한다.
obj2.sort_index(ascending=False)

d    30
c    40
b    20
a    10
dtype: int64

In [23]:
data = np.arange(8).reshape(2,4)

In [24]:
data

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
frame = pd.DataFrame(data,index=['three','one'], columns=list('dabc'))

In [28]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [31]:
frame.sort_values(by="a",ascending=False) #a를 기준으로

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [34]:
data1 = data.astype(np.float) #실수 형태로 바꾼다.

In [35]:
data1

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]])

In [37]:
data1[0,1] = np.nan

In [39]:
data1

array([[ 0., nan,  2.,  3.],
       [ 4.,  5.,  6.,  7.]])

In [40]:
frame1 = pd.DataFrame(data1, index=['three','one'],columns=list('abcd'))

In [51]:
frame1.sort_values(by='a',) #NaN이 제일 큰 수로 취급된다.

a    b    c    d
three  0.0  NaN  2.0  3.0
one    4.0  5.0  6.0  7.0

In [47]:
frame1.sort_values(by='a',na_position='last') 

a    b    c    d
three  0.0  NaN  2.0  3.0
one    4.0  5.0  6.0  7.0

In [49]:
frame1.sort_values(by='a',na_position='first') 

a    b    c    d
three  0.0  NaN  2.0  3.0
one    4.0  5.0  6.0  7.0

In [52]:
frame2 = pd.DataFrame([{'가':3, '나':15, '다': 3},
                       {'가':3, '나':10, '다': 5},
                       {'가':1, '나':20, '다': 5},
                       {'가':2, '나':15, '다': 7},
                       {'가':2, '나':100,'다': 9}])

frame2.sort_values(['가','나'],ascending=[False,True]) #가 기준으로 내림차순 후 그 안에서 다시 나 기준으로 오름차순.

가    나  다
1  3   10  5
0  3   15  3
3  2   15  7
4  2  100  9
2  1   20  5

In [53]:
frame3 = pd.DataFrame([{'가':3, '나':15, '다': 3},
                       {'가':3, '나':10, '다': 5},
                       {'가':1, '나':20, '다': 5},
                       {'가':2, '나':15, '다': 7},
                       {'가':2, '나':100,'다': 9}],
                     columns=['다','가','나'])

In [54]:
frame3

다  가    나
0  3  3   15
1  5  3   10
2  5  1   20
3  7  2   15
4  9  2  100

In [56]:
frame3 = pd.DataFrame([{'가':3, '나':15, '다': 3},
                       {'가':3, '나':10, '다': 5},
                       {'가':1, '나':20, '다': 5},
                       {'가':2, '나':15, '다': 7},
                       {'가':2, '나':100,'다': 9}],
                     columns=list('가나다'))
frame3.sort_index(axis=0) #zip함수로 한번에 만들 수 있다.

가    나  다
0  3   15  3
1  3   10  5
2  1   20  5
3  2   15  7
4  2  100  9

In [57]:
frame3

가    나  다
0  3   15  3
1  3   10  5
2  1   20  5
3  2   15  7
4  2  100  9

In [58]:
frame3.sort_index(axis=0) #index를 정렬 해봤자 이미 정렬 되어있어서 효과가 없어 보이는 거 뿐임
#값의 기준이 아님

가    나  다
0  3   15  3
1  3   10  5
2  1   20  5
3  2   15  7
4  2  100  9

In [60]:
frame3.sort_index(axis=1)

가    나  다
0  3   15  3
1  3   10  5
2  1   20  5
3  2   15  7
4  2  100  9

In [61]:
frame3.sort_index().sort_index(axis=1)

가    나  다
0  3   15  3
1  3   10  5
2  1   20  5
3  2   15  7
4  2  100  9

이름    학번  과제건수  점수
0  길동  2012     1  25
1  옥주  2012     5  94
2  현웅  2013     2  57
3  주몽  2014     3  62
4  지원  2014     4  70

In [63]:
data1 = {'이름': ['길동', '옥주', '현웅', '주몽', '지원'], #순서가 없다
        '학번': [2012, 2012, 2013, 2014, 2014], 
        '과제건수': [1, 5, 2, 3, 4],
        '점수': [25, 94, 57, 62, 70]}
frame3 = pd.DataFrame(data1, columns=list(#~~~))# 순서 만들기
frame3

SyntaxError: unexpected EOF while parsing (<ipython-input-63-d43cd15cd2a0>, line 6)

In [78]:
data1 = {'이름': ['길동', '옥주', '현웅', '주몽', '지원'], #순서가 없다
        '학번': [2012, 2012, 2013, 2014, 2014], 
        '과제건수': [1, 5, 2, 3, 4],
        '점수': [25, 94, 57, 62, 70]}
frame3 = pd.DataFrame(data1)
frame3

이름    학번  과제건수  점수
0  길동  2012     1  25
1  옥주  2012     5  94
2  현웅  2013     2  57
3  주몽  2014     3  62
4  지원  2014     4  70

In [79]:
frame3['점수'].rank(ascending=False)

0    5.0
1    1.0
2    4.0
3    3.0
4    2.0
Name: 점수, dtype: float64

In [80]:
frame3['순위'] =frame3['점수'].rank(ascending=False)

In [81]:
frame3

이름    학번  과제건수  점수   순위
0  길동  2012     1  25  5.0
1  옥주  2012     5  94  1.0
2  현웅  2013     2  57  4.0
3  주몽  2014     3  62  3.0
4  지원  2014     4  70  2.0

In [82]:
frame3.sort_values(by='순위')

이름    학번  과제건수  점수   순위
1  옥주  2012     5  94  1.0
4  지원  2014     4  70  2.0
3  주몽  2014     3  62  3.0
2  현웅  2013     2  57  4.0
0  길동  2012     1  25  5.0

In [84]:
frame4 =frame3.sort_values(by='순위') #어지럽힌 인덱스를 다시 새로 붙이기
frame4.index = [0,1,2,3,4]
frame4

이름    학번  과제건수  점수   순위
0  옥주  2012     5  94  1.0
1  지원  2014     4  70  2.0
2  주몽  2014     3  62  3.0
3  현웅  2013     2  57  4.0
4  길동  2012     1  25  5.0

In [85]:
data = {'가' : pd.Series([1.], index=['a']),
        '나' : pd.Series([1., 2.], index=['a', 'b']),
        '다' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(data)

In [87]:
df #값을 다 안채우면 NaN 객체가 만들어진다.

가    나    다
a  1.0  1.0  1.0
b  NaN  2.0  2.0
c  NaN  NaN  3.0
d  NaN  NaN  4.0

In [90]:
df['나']=pd.Series([3,4,5,6],index=list('abcd'),dtype='float')
df

가    나    다
a  1.0  3.0  1.0
b  NaN  4.0  2.0
c  NaN  5.0  3.0
d  NaN  6.0  4.0

In [108]:
df1 = df[['나','다']] #펜시 검색하면 형식은 그대로 나온다.

In [109]:
df1

나    다
a  3.0  1.0
b  4.0  2.0
c  5.0  3.0
d  6.0  4.0

In [118]:
df1 = df[['나','다']]
df1.at['a','나'] = 100

In [119]:
df1

나    다
a  100.0  1.0
b    4.0  2.0
c    5.0  3.0
d    6.0  4.0

In [131]:
df1.at[['b','c'],['나']] = 99 #효과가 적용되나 에러코드가 발생할 수도 있다. 책에 오류가 안나는 방법이 적혀있다.

In [132]:
a= df1.나.shift(-1) #위로 한행씩

In [133]:
a

a    99.0
b    99.0
c     NaN
d     NaN
Name: 나, dtype: float64

In [134]:
df1['나'] = a
df1

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


나    다
a  99.0  1.0
b  99.0  2.0
c   NaN  3.0
d   NaN  4.0

In [135]:
#2x3, 3x2 를 합치려면 인덱스를 재 구성한다.
#사전객체안에 사전객체를 넣어 데이터 프레임의 매개변수에 넣으면 인덱스 칼람 다 완성되지만 사전객체 하나 넣으면 키 값이 인덱스로 들어가고 인덱스는 자동으로 써진다.

In [138]:
df = pd.DataFrame({'foo': ['one','one','one','two','two','two'],
                           'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                           'baz': [1, 2, 3, 4, 5, 6]}) #중복을 값을 중첩제거하여 6개의 값이 들어갈 값 2x3이 딱 된다.

In [139]:
df.pivot(index='foo',columns='bar',values='baz')

bar  A  B  C
foo         
one  1  2  3
two  4  5  6

In [158]:
df1 = pd.DataFrame({'foo': ['one','one','one','two','two','two'],
                           'bar': ['A', 'B', 'A', 'A', 'B', 'C'],
                           'baz': [1, 2, 3, 4, 5, 6]}) #(A값)중복이 제대로 안된놈이 있어서 안된다.

In [159]:
try : 
    df1.pivot('foo','bar','baz')
except Exception as e :
    print(e) #짝이 안맞아서 안만들어진다.

Index contains duplicate entries, cannot reshape


In [160]:
df1.drop_duplicates(['foo','bar']) #제대로 만들어준다.
df1

foo bar  baz
0  one   A    1
1  one   B    2
2  one   A    3
3  two   A    4
4  two   B    5
5  two   C    6

In [161]:
df1.drop_duplicates(['foo','bar'],keep='first')
df1

foo bar  baz
0  one   A    1
1  one   B    2
2  one   A    3
3  two   A    4
4  two   B    5
5  two   C    6

In [162]:
df1 = df1.drop_duplicates(['foo','bar']) #중복이 엇갈릴 경우 제거
df1.pivot('foo','bar','baz')#그 후 다시 중복 고려 표 만들기.

bar    A    B    C
foo               
one  1.0  2.0  NaN
two  4.0  5.0  6.0

In [147]:
#재구성에는 스택과 언스택이 있다. 멀티인덱스에서만 가능하다.

In [148]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.shape

(891, 15)

In [149]:
titaic_s =  titanic.groupby('survived').mean()

In [150]:
titaic_s.pivot(index='pclass', columns='age', values='fare')

age       28.343690  30.626179
pclass                        
1.950292  48.395408        NaN
2.531876        NaN  22.117887

In [153]:
titanic_c = titanic.pivot_table(values='survived',
                               index='sex', 
                               columns='class',
                               aggfunc='sum')

In [154]:
titanic_c

class   First  Second  Third
sex                         
female     91      70     72
male       45      17     47

In [155]:
titanic_.sum().sum()#원본과 재구성의 값은 같다.

342

In [156]:
titanic['survived'].sum()

342