###형태를 합치기 위해 재 구조화

In [198]:
import pandas as pd
import numpy as np
obj1 = pd.Series([40,10,20,30],index=list('가나다라'))
obj1.sort_values(ascending=False)

가    40
라    30
다    20
나    10
dtype: int64

In [199]:
obj1.argsort() #인덱스가 아닌 포지션 레이블

가    1
나    2
다    3
라    0
dtype: int64

In [200]:
obj1.idxmin()

'나'

In [201]:
obj1.idxmax()

'가'

In [202]:
obj2=pd.Series([40,10,20,30],index=list('cabd'))
obj2

c    40
a    10
b    20
d    30
dtype: int64

In [203]:
#슬라이딩 하기 전에 정렬 해야한다.
obj2.sort_index(ascending=False)

d    30
c    40
b    20
a    10
dtype: int64

In [204]:
data = np.arange(8).reshape(2,4)

In [205]:
data

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [206]:
frame = pd.DataFrame(data,index=['three','one'], columns=list('dabc'))

In [207]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [208]:
frame.sort_values(by="a",ascending=False) #a를 기준으로

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [209]:
data1 = data.astype(np.float) #실수 형태로 바꾼다.

In [210]:
data1

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]])

In [211]:
data1[0,1] = np.nan

In [212]:
data1

array([[ 0., nan,  2.,  3.],
       [ 4.,  5.,  6.,  7.]])

In [213]:
frame1 = pd.DataFrame(data1, index=['three','one'],columns=list('abcd'))

In [214]:
frame1.sort_values(by='a',) #NaN이 제일 큰 수로 취급된다.

a    b    c    d
three  0.0  NaN  2.0  3.0
one    4.0  5.0  6.0  7.0

In [215]:
frame1.sort_values(by='a',na_position='last') 

a    b    c    d
three  0.0  NaN  2.0  3.0
one    4.0  5.0  6.0  7.0

In [216]:
frame1.sort_values(by='a',na_position='first') 

a    b    c    d
three  0.0  NaN  2.0  3.0
one    4.0  5.0  6.0  7.0

In [217]:
frame2 = pd.DataFrame([{'가':3, '나':15, '다': 3},
                       {'가':3, '나':10, '다': 5},
                       {'가':1, '나':20, '다': 5},
                       {'가':2, '나':15, '다': 7},
                       {'가':2, '나':100,'다': 9}])

frame2.sort_values(['가','나'],ascending=[False,True]) #가 기준으로 내림차순 후 그 안에서 다시 나 기준으로 오름차순.

가    나  다
1  3   10  5
0  3   15  3
3  2   15  7
4  2  100  9
2  1   20  5

In [218]:
frame3 = pd.DataFrame([{'가':3, '나':15, '다': 3},
                       {'가':3, '나':10, '다': 5},
                       {'가':1, '나':20, '다': 5},
                       {'가':2, '나':15, '다': 7},
                       {'가':2, '나':100,'다': 9}],
                     columns=['다','가','나'])

In [219]:
frame3

다  가    나
0  3  3   15
1  5  3   10
2  5  1   20
3  7  2   15
4  9  2  100

In [220]:
frame3 = pd.DataFrame([{'가':3, '나':15, '다': 3},
                       {'가':3, '나':10, '다': 5},
                       {'가':1, '나':20, '다': 5},
                       {'가':2, '나':15, '다': 7},
                       {'가':2, '나':100,'다': 9}],
                     columns=list('가나다'))
frame3.sort_index(axis=0) #zip함수로 한번에 만들 수 있다.

가    나  다
0  3   15  3
1  3   10  5
2  1   20  5
3  2   15  7
4  2  100  9

In [221]:
frame3

가    나  다
0  3   15  3
1  3   10  5
2  1   20  5
3  2   15  7
4  2  100  9

In [222]:
frame3.sort_index(axis=0) #index를 정렬 해봤자 이미 정렬 되어있어서 효과가 없어 보이는 거 뿐임
#값의 기준이 아님

가    나  다
0  3   15  3
1  3   10  5
2  1   20  5
3  2   15  7
4  2  100  9

In [223]:
frame3.sort_index(axis=1)

가    나  다
0  3   15  3
1  3   10  5
2  1   20  5
3  2   15  7
4  2  100  9

In [224]:
frame3.sort_index().sort_index(axis=1)

가    나  다
0  3   15  3
1  3   10  5
2  1   20  5
3  2   15  7
4  2  100  9

In [225]:
data1 = {'이름': ['길동', '옥주', '현웅', '주몽', '지원'], #순서가 없다
        '학번': [2012, 2012, 2013, 2014, 2014], 
        '과제건수': [1, 5, 2, 3, 4],
        '점수': [25, 94, 57, 62, 70]}
frame3 = pd.DataFrame(data1, columns=list(#~~~))# 순서 만들기
frame3

SyntaxError: unexpected EOF while parsing (<ipython-input-225-d43cd15cd2a0>, line 6)

In [226]:
data1 = {'이름': ['길동', '옥주', '현웅', '주몽', '지원'], #순서가 없다
        '학번': [2012, 2012, 2013, 2014, 2014], 
        '과제건수': [1, 5, 2, 3, 4],
        '점수': [25, 94, 57, 62, 70]}
frame3 = pd.DataFrame(data1)
frame3

이름    학번  과제건수  점수
0  길동  2012     1  25
1  옥주  2012     5  94
2  현웅  2013     2  57
3  주몽  2014     3  62
4  지원  2014     4  70

In [227]:
frame3['점수'].rank(ascending=False)

0    5.0
1    1.0
2    4.0
3    3.0
4    2.0
Name: 점수, dtype: float64

In [228]:
frame3['순위'] =frame3['점수'].rank(ascending=False)

In [229]:
frame3

이름    학번  과제건수  점수   순위
0  길동  2012     1  25  5.0
1  옥주  2012     5  94  1.0
2  현웅  2013     2  57  4.0
3  주몽  2014     3  62  3.0
4  지원  2014     4  70  2.0

In [230]:
frame3.sort_values(by='순위')

이름    학번  과제건수  점수   순위
1  옥주  2012     5  94  1.0
4  지원  2014     4  70  2.0
3  주몽  2014     3  62  3.0
2  현웅  2013     2  57  4.0
0  길동  2012     1  25  5.0

In [231]:
frame4 =frame3.sort_values(by='순위') #어지럽힌 인덱스를 다시 새로 붙이기
frame4.index = [0,1,2,3,4]
frame4

이름    학번  과제건수  점수   순위
0  옥주  2012     5  94  1.0
1  지원  2014     4  70  2.0
2  주몽  2014     3  62  3.0
3  현웅  2013     2  57  4.0
4  길동  2012     1  25  5.0

In [232]:
data = {'가' : pd.Series([1.], index=['a']),
        '나' : pd.Series([1., 2.], index=['a', 'b']),
        '다' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(data)

In [233]:
df #값을 다 안채우면 NaN 객체가 만들어진다.

가    나    다
a  1.0  1.0  1.0
b  NaN  2.0  2.0
c  NaN  NaN  3.0
d  NaN  NaN  4.0

In [234]:
df['나']=pd.Series([3,4,5,6],index=list('abcd'),dtype='float')
df

가    나    다
a  1.0  3.0  1.0
b  NaN  4.0  2.0
c  NaN  5.0  3.0
d  NaN  6.0  4.0

In [235]:
df1 = df[['나','다']] #펜시 검색하면 형식은 그대로 나온다.

In [236]:
df1

나    다
a  3.0  1.0
b  4.0  2.0
c  5.0  3.0
d  6.0  4.0

In [237]:
df1 = df[['나','다']]
df1.at['a','나'] = 100

In [238]:
df1

나    다
a  100.0  1.0
b    4.0  2.0
c    5.0  3.0
d    6.0  4.0

In [239]:
df1.at[['b','c'],['나']] = 99 #효과가 적용되나 에러코드가 발생할 수도 있다. 책에 오류가 안나는 방법이 적혀있다.

D:\anaconda\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
D:\anaconda\lib\site-packages\pandas\core\frame.py:2823: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.loc[index, col] = value


In [240]:
a= df1.나.shift(-1) #위로 한행씩

In [241]:
a

a    99.0
b    99.0
c     6.0
d     NaN
Name: 나, dtype: float64

In [242]:
df1['나'] = a
df1

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


나    다
a  99.0  1.0
b  99.0  2.0
c   6.0  3.0
d   NaN  4.0

In [243]:
#2x3, 3x2 를 합치려면 인덱스를 재 구성한다.
#사전객체안에 사전객체를 넣어 데이터 프레임의 매개변수에 넣으면 인덱스 칼람 다 완성되지만 사전객체 하나 넣으면 키 값이 인덱스로 들어가고 인덱스는 자동으로 써진다.

In [244]:
df = pd.DataFrame({'foo': ['one','one','one','two','two','two'],
                           'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                           'baz': [1, 2, 3, 4, 5, 6]}) #중복을 값을 중첩제거하여 6개의 값이 들어갈 값 2x3이 딱 된다.

In [245]:
df.pivot(index='foo',columns='bar',values='baz')

bar  A  B  C
foo         
one  1  2  3
two  4  5  6

In [246]:
df1 = pd.DataFrame({'foo': ['one','one','one','two','two','two'],
                           'bar': ['A', 'B', 'A', 'A', 'B', 'C'],
                           'baz': [1, 2, 3, 4, 5, 6]}) #(A값)중복이 제대로 안된놈이 있어서 안된다.

In [247]:
try : 
    df1.pivot('foo','bar','baz')
except Exception as e :
    print(e) #짝이 안맞아서 안만들어진다.

Index contains duplicate entries, cannot reshape


In [248]:
df1.drop_duplicates(['foo','bar']) #제대로 만들어준다.
df1

foo bar  baz
0  one   A    1
1  one   B    2
2  one   A    3
3  two   A    4
4  two   B    5
5  two   C    6

In [249]:
df1.drop_duplicates(['foo','bar'],keep='first')
df1

foo bar  baz
0  one   A    1
1  one   B    2
2  one   A    3
3  two   A    4
4  two   B    5
5  two   C    6

In [250]:
df1 = df1.drop_duplicates(['foo','bar']) #중복이 엇갈릴 경우 제거
df1.pivot('foo','bar','baz')#그 후 다시 중복 고려 표 만들기.

bar    A    B    C
foo               
one  1.0  2.0  NaN
two  4.0  5.0  6.0

In [251]:
#재구성에는 스택과 언스택이 있다. 멀티인덱스에서만 가능하다.

In [252]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.shape

(891, 15)

In [253]:
titaic_s =  titanic.groupby('survived').mean()

In [254]:
titaic_s.pivot(index='pclass', columns='age', values='fare')

age       28.343690  30.626179
pclass                        
1.950292  48.395408        NaN
2.531876        NaN  22.117887

In [255]:
titanic_c = titanic.pivot_table(values='survived',
                               index='sex', 
                               columns='class',
                               aggfunc='sum')

In [256]:
titanic_c

class   First  Second  Third
sex                         
female     91      70     72
male       45      17     47

In [257]:
titaic_s .sum().sum()#원본과 재구성의 값은 같다.

138.02036020522004

In [258]:
titanic['survived'].sum()

342

In [259]:
titanic = sns.load_dataset('titanic')
titaic_s =  titanic.groupby('survived').mean() #수치값만 평균처리

In [260]:
titaic_s.pivot(index='pclass', columns='age', values='fare')

age       28.343690  30.626179
pclass                        
1.950292  48.395408        NaN
2.531876        NaN  22.117887

In [261]:
titanic_ = titanic.pivot_table(values='survived',
                               index='sex', 
                               columns='class',
                               aggfunc='sum') #피봇 테이블을 이용하면 한번에 가능

In [262]:
weight = pd.read_csv('weight_loss.csv',encoding='cp949')

In [263]:
weight.head()

이름   월   주  몸무게
0  지완  1월  1주   70
1  찬준  1월  1주   60
2  지완  1월  2주   69
3  찬준  1월  2주   59
4  지완  1월  3주   69

In [264]:
week4 = weight.query('주 == "4주"')

In [265]:
week4

이름   월   주  몸무게
6   지완  1월  4주   69
7   찬준  1월  4주   59
14  지완  2월  4주   66
15  찬준  2월  4주   56
22  지완  3월  4주   64
23  찬준  3월  4주   54
30  지완  4월  4주   62
31  찬준  4월  4주   52

In [266]:
week4.pivot(index='월',columns="이름",values='몸무게')

이름  지완  찬준
월         
1월  69  59
2월  66  56
3월  64  54
4월  62  52

In [267]:
#멀티인덱스의 컬럼의 인덱스를 행 단위 인덱스로 추가하는 것을 스택이라하며 컬럼이 없어지면 시리즈로 바뀐다. 아마 이 시리즈들을 모으면 다시 데이터 프레임이 되는건가?
#행 INDEX가 컬럼INDEX로 추가되는 것을 언스텍 인덱스라고 한다. 또 시리즈로 바뀐다.

In [268]:
week5 = week4.set_index(['이름','월'])

In [269]:
week5

주  몸무게
이름 월          
지완 1월  4주   69
찬준 1월  4주   59
지완 2월  4주   66
찬준 2월  4주   56
지완 3월  4주   64
찬준 3월  4주   54
지완 4월  4주   62
찬준 4월  4주   52

In [270]:
week5_st = week5.stack()

In [271]:
week5_st #열에 대한 인덱스가 사라져서 (스택) 시리즈 객체로 바뀌었다.(데이터 프레임 함수 사용 불가능)

이름  월      
지완  1월  주      4주
        몸무게    69
찬준  1월  주      4주
        몸무게    59
지완  2월  주      4주
        몸무게    66
찬준  2월  주      4주
        몸무게    56
지완  3월  주      4주
        몸무게    64
찬준  3월  주      4주
        몸무게    54
지완  4월  주      4주
        몸무게    62
찬준  4월  주      4주
        몸무게    52
dtype: object

In [272]:
type(week5_st)

pandas.core.series.Series

In [273]:
week5_st.index.get_level_values #계속 확인해보자

<bound method MultiIndex.get_level_values of MultiIndex(levels=[['지완', '찬준'], ['1월', '2월', '3월', '4월'], ['주', '몸무게']],
           codes=[[0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1], [0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]],
           names=['이름', '월', None])>

In [274]:
week5_st.index.get_level_values(1)

Index(['1월', '1월', '1월', '1월', '2월', '2월', '2월', '2월', '3월', '3월', '3월', '3월',
       '4월', '4월', '4월', '4월'],
      dtype='object', name='월')

In [275]:
to_week5 = week5_st.to_frame()

In [276]:
to_week5

0
이름 월         
지완 1월 주    4주
      몸무게  69
찬준 1월 주    4주
      몸무게  59
지완 2월 주    4주
      몸무게  66
찬준 2월 주    4주
      몸무게  56
지완 3월 주    4주
      몸무게  64
찬준 3월 주    4주
      몸무게  54
지완 4월 주    4주
      몸무게  62
찬준 4월 주    4주
      몸무게  52

In [277]:
to_week5.index.levels

FrozenList([['지완', '찬준'], ['1월', '2월', '3월', '4월'], ['주', '몸무게']])

In [278]:
to_week5.columns

RangeIndex(start=0, stop=1, step=1)

In [279]:
#스택 언스택 자체가 멀티 인덱스로 만들어지니 좀 더 멀티스럽게 다룰 수 있다.

In [280]:
week5

주  몸무게
이름 월          
지완 1월  4주   69
찬준 1월  4주   59
지완 2월  4주   66
찬준 2월  4주   56
지완 3월  4주   64
찬준 3월  4주   54
지완 4월  4주   62
찬준 4월  4주   52

In [281]:
week5_un = week5.unstack()

In [282]:
week5_un.head() #레벨이 정해져있는데 우선 한번 언스택 하니 행 쪽 1번 레벨이 컬럼으로 가고 한번 더 하면 아마 이름이 또 컬럼으로 가서 행이 없어서 데이터 프레임이 풀려 시리즈로 바뀔 것이다.

주             몸무게            
월   1월  2월  3월  4월  1월  2월  3월  4월
이름                                
지완  4주  4주  4주  4주  69  66  64  62
찬준  4주  4주  4주  4주  59  56  54  52

In [283]:
week5_un_un = week5.unstack().unstack()

In [284]:
type(week5_un_un)

pandas.core.series.Series

In [285]:
week5_un_un.values

array(['4주', '4주', '4주', '4주', '4주', '4주', '4주', '4주', 69, 59, 66, 56, 64,
       54, 62, 52], dtype=object)

In [286]:
#참고로 다시 데이터프레임으로 만들면 빈 행 인덱스는 레인지 타입으로 0부터 숫자가 채워진다.

In [287]:
week4_s = week4['몸무게']

In [288]:
week4_s

6     69
7     59
14    66
15    56
22    64
23    54
30    62
31    52
Name: 몸무게, dtype: int64

In [289]:
week4_s.index = week5['몸무게'].index #시리즈 행에 또 붙여넣어 멀티인덱스를 만든다.

In [290]:
week4_s

이름  월 
지완  1월    69
찬준  1월    59
지완  2월    66
찬준  2월    56
지완  3월    64
찬준  3월    54
지완  4월    62
찬준  4월    52
Name: 몸무게, dtype: int64

In [291]:
week4_s.unstack() #스택 언스택에 데이터프레임으로 자동으로 만들어주는 기능도 있나? 아니면 행을 옮겨 없던 컬럼으로 만들어주면 알아서 데이터 프레임이 되는 것인가? 데이터 프레임 만드는 to_frame 기능을 사용하면 레인지로 새로 만들어주는 거랑 다르네.

월   1월  2월  3월  4월
이름                
지완  69  66  64  62
찬준  59  56  54  52

In [292]:
type(week4_s.unstack())

pandas.core.frame.DataFrame

In [293]:
week4_s.unstack(level=0)

이름  지완  찬준
월         
1월  69  59
2월  66  56
3월  64  54
4월  62  52

In [312]:
week4_s.unstack(level=1) #레빌 0, 1을 행으로 취급하면 제일 먼저가 0이고 그 뒤가 1이고 컬럼으로 옮기면 걸럼의 0이 되는 것인가?

월   1월  2월  3월  4월
이름                
지완  69  66  64  62
찬준  59  56  54  52